---
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  iam_profile_name: <%= ENV['IAM_PROFILE_NAME'] %>

provisioner:
  name: chef_zero
  github_owner: "chef"
  github_repo: "chef"
  refname: <%= ENV['TRAVIS_COMMIT'] %>
  data_path: test/fixtures
# disable file provider diffs so we don't overflow travis' line limit
  client_rb:
    diff_disabled: true

transport:
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

platforms:
  - name: ubuntu-12.04
    driver_plugin: ec2
    driver_config:
      region: "us-west-2"
      availability_zone: "us-west-2a"
      security_group_ids: ["travis-ci"]
  - name: centos-6.4
    driver_plugin: ec2
    driver_config:
      region: "us-west-2"
      availability_zone: "us-west-2a"
      security_group_ids: ["travis-ci"]

suites:
  - name: webapp
    run_list:
      - recipe[apt::default]
      - recipe[webapp::default]
    attributes:
